appnametochange:
  image:
    repository: ghcr.io/ccollot/appnametochange
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.1.0"
  replicaCount: 1
  service:
    port: 8080
  resources:
    requests:
      cpu: 0.05
      memory: 100Mi
    limits:
      memory: 100Mi
